sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t guslegge/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true guslegge/react-test npm test

after_sucess:
  - docker build -t guslegge/multi-client ./client
  - docker build -t guslegge/multi-nginx ./nginx
  - docker build -t guslegge/multi-server ./server
  - docker build -t guslegge/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub
  - docker push guslegge/multi-client
  - docker push guslegge/multi-nginx
  - docker push guslegge/multi-server
  - docker push guslegge/multi-worker


deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-531333889525'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY